name: MERN Docker CI/CD NotesApp Pipeline

on:
  push:
    branches: [master]

jobs:
  build-frontend:
    name: ğŸ³ Build & Push Frontend Docker Image
    runs-on: ubuntu-latest
    if: |
      contains(toJson(github.event.commits.*.modified), 'frontend-view/') ||
      contains(toJson(github.event.commits.*.added), 'frontend-view/') ||
      contains(toJson(github.event.commits.*.removed), 'frontend-view/')
    steps:
      - name: ğŸ§¾ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: ğŸ—ï¸ Build Frontend Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-frontend:latest ./frontend-view

      - name: ğŸ—ï¸ Push Frontend Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-frontend:latest

  build-backend:
    name: ğŸ³ Build & Push Backend Docker Image
    runs-on: ubuntu-latest
    if: |
      contains(toJson(github.event.commits.*.modified), 'backend-app/') ||
      contains(toJson(github.event.commits.*.added), 'backend-app/') ||
      contains(toJson(github.event.commits.*.removed), 'backend-app/')
    steps:
      - name: ğŸ§¾ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: ğŸ—ï¸ Build Backend Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-backend:latest ./backend-app

      - name: ğŸ—ï¸ Push Backend Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-backend:latest
